In [ ]:
NAME = "Wajahat Khan"

---

# Lab 6: Skip Gram

**Please read the following instructions very carefully**

## Working on the assignment / FAQs
- **Always use the seed/random_state as *42* wherever applicable** (This is to ensure repeatability in answers, across students and coding environments)
- The type of question and the points they carry are indicated in each question cell
- To avoid any ambiguity, each question also specifies what *value* must be set. Note that these are dummy values and not the answers
- If an autograded question has multiple answers (due to differences in handling NaNs, zeros etc.), all answers will be considered.
- You can delete the `raise NotImplementedError()`
- **Submitting the assignment** : Download the '.ipynb' file from Colab and upload it to bcourses. Do not delete any outputs from cells before submitting.
- That's about it. Happy coding!


Available software:
 - Python's Gensim module: https://radimrehurek.com/gensim/ (install using pip)

_Note: The most important hyper parameters of skip-gram/CBOW are vector size and windows size_


In [1]:
!pip install gensim
import pandas as pd
import numpy as np
import gensim

In [2]:
import gensim.downloader as api
model = api.load('word2vec-google-news-300') # this step might take ~10-15 minutes

### **Q1 (1 point)**
Find the cosine similarity between the following word pairs

- (France, England)
- (come, go)
- (England, London)
- (France, Rocket)
- (big, bigger)

In [67]:
#Replace 0 with the code / value; Do not delete this cell
similarity_pair1 = model.similarity("France", "England")
similarity_pair2 = model.similarity("come", "go")
similarity_pair3 = model.similarity("England", "London")
similarity_pair4 = model.similarity("France", "Rocket")
similarity_pair5 = model.similarity("big", "bigger")

In [68]:
#This is an autograded cell, do not edit/delete
print(similarity_pair1, similarity_pair2, similarity_pair3, similarity_pair4, similarity_pair5)

0.39804947 0.6604678 0.4399286 0.071141735 0.68423855


### **Q2 (1 point)**
Write an expression to extract the vector representations of the words:

- France
- England
- smaller
- bigger
- rocket
- big

Get only the first 5 elements for each vector representation.

In [69]:
#Replace 0 with the code / value to get the first 5 elements of each vector; Do not delete this cell
vector_1 = model["France"][:5]
vector_2 = model["England"][:5]
vector_3 = model["smaller"][:5]
vector_4 = model["bigger"][:5]
vector_5 = model["rocket"][:5]
vector_6 = model["big"][:5]

In [70]:
#This is an autograded cell, do not edit/delete
print(vector_1)
print(vector_2)
print(vector_3)
print(vector_4)
print(vector_5)
print(vector_6)


[0.04858398 0.07861328 0.32421875 0.03491211 0.07714844]
[-0.19824219  0.11523438  0.0625     -0.05834961  0.2265625 ]
[-0.05004883  0.03417969 -0.0703125   0.17578125  0.00689697]
[-0.06542969 -0.09521484 -0.06225586  0.16210938  0.01989746]
[-0.03198242  0.27148438 -0.2890625  -0.15429688  0.16894531]
[ 0.11132812  0.10595703 -0.07373047  0.18847656  0.07666016]


### **Q3 (1 point)**
Find the euclidean distances between the word pairs :

- (France, England)
- (smaller, bigger)
- (England, London)
- (France, Rocket)
- (big, bigger)


In [71]:
#Replace 0 with the code / value; Do not delete this cell

from scipy.spatial import distance ## --> I got this from scikit learn 
# link: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.euclidean_distances.html

eu_dist1 = distance.euclidean(model["France"], model["England"])
eu_dist2 = distance.euclidean(model["smaller"], model["bigger"])
eu_dist3 = distance.euclidean(model["England"], model["London"])
eu_dist4 = distance.euclidean(model["France"], model["Rocket"])
eu_dist5 = distance.euclidean(model["big"], model["bigger"])

In [72]:
#This is an autograded cell, do not edit / delete
print(eu_dist1)
print(eu_dist2)
print(eu_dist3)
print(eu_dist4)
print(eu_dist5)


3.015106678009033
1.8618743419647217
2.875283718109131
3.892071008682251
1.9586496353149414


### **Q4 (1 point)**
Time to dabble with the power of Word2Vec. Find the 2 closest words  for the following conditions:  
- (King - Man + Queen)
- (bigger - big + small)
- (waiting - wait + run)
- (Texas + Milwaukee – Wisconsin)

Note: If your kernel crashes due to low memory and restarts, reload the model from the top and try running this part again.

In [73]:
#Replace 0 with the code / value; Do not delete this cell

closest1 = model.most_similar(positive = ['King', 'Queen'], negative = ['Man'])[:2] 
closest2 = model.most_similar(positive = ['bigger', 'small'], negative = ['big'])[:2] 
closest3 = model.most_similar(positive = ['waiting', 'run'], negative = ['wait'])[:2] 
closest4 = model.most_similar(positive = ['Texas', 'Milwaukee'], negative = ['Wisconsin'])[:2]

In [74]:
#This is an autograded cell, do not edit/delete
print(closest1)
print(closest2)
print(closest3)
print(closest4)

[('Queen_Elizabeth', 0.525791585445404), ('monarch', 0.5004087090492249)]
[('larger', 0.7402471899986267), ('smaller', 0.7329993844032288)]
[('running', 0.5654535889625549), ('runs', 0.49640005826950073)]
[('Houston', 0.7767744660377502), ('Fort_Worth', 0.7270510792732239)]


### **Q5 (3 points)**
Using the vectors for the words in the Google News dataset, apply K-means clustering (K=2) and find the top 5 most representative words/phrases of each cluster.

*Note: Since there are ~3Mil words in the vocabulary, you can downsample it to 25k randomly selected words*  \\
*Hint: The "similar_by_vector" method might be useful*

**Do not delete the below cell**

In [102]:
# Replace 0 with the code / value; Do not delete this cell
# YOUR CODE HERE
from sklearn.cluster import KMeans
from random import sample

# https://radimrehurek.com/gensim/models/keyedvectors.html

sampled_words = sample(model.index_to_key, 2500)
kmeans = KMeans(n_clusters= 2, n_init=10, 
                random_state=42).fit([model[word] for word in sampled_words])

most_rep_cluster1 = model.similar_by_vector(kmeans.cluster_centers_[0], topn=5)
most_rep_cluster2 = model.similar_by_vector(kmeans.cluster_centers_[1], topn=5)

In [103]:
#This is an autograded cell, do not edit/delete
print(most_rep_cluster1)
print(most_rep_cluster2)

[('Emil_Protalinski_Published', 0.9183648228645325), ('By_HuDie_####-##-##', 0.9160116314888), ('By_XiaoBing_####-##-##', 0.9148709177970886), ('By_QianMian_####-##-##', 0.9128484129905701), ('STACY_LEE', 0.9120089411735535)]
[('http_dol##.net_index###.html_http', 0.9203289747238159), ('dol##.net_index####.html_http_dol##.net', 0.910273551940918), ('index###.html_http_dol##.net_index###.html', 0.9092676043510437), ('Deltagen_undertakes', 0.9084193110466003), ('By_TRICIA_SCRUGGS', 0.9058576226234436)]


### **Q6 (1 point)**
What loss function does the skipgram model use and briefly describe what this function is minimizing.

**Do not delete the below cell**


**The skipgram model uses the funcation called negative sampling, which basically reduces the complexity of the training model, its like the softmax loss funcation in that way. The purpose of it is to train the word embeddings so they compare the relation between the words, like the simarily score for King and Queen we did above. THe model will increase if it doesn't classify correctly.** 

### **Bonus Question (1 point)**
Find at least 2 interesting word vec combinations like the ones given in Q4

**Do not delete the below cell**

In [65]:
# YOUR CODE HERE
# "Paris - France + Italy"
# "Cricket - India + Pakistan" ## was trying to the current world cup but it doesn't have the names

closest1 = model.most_similar(positive = ['Paris', 'Italy'], negative = ['France'])[:2] 
closest2 = model.most_similar(positive = ['ODI', 'Pakistan'], negative = ['India'])[:2] 

In [66]:
print(closest1)
print(closest2)

[('Milan', 0.7222141623497009), ('Rome', 0.702830970287323)]
[('Afridi', 0.6969332098960876), ('Inzamam', 0.6848824620246887)]
